name: Build and Test

on:
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Install Xcodecoverageconverter
        run: brew install twittemb/formulae/Xcodecoverageconverter
      - name: Checkout
        uses: actions/checkout@v3
      - name: select latest xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.0'
      - name: Kill Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Build & Test
        run: |
          xcodebuild clean test \
            -project 'CardFortress.xcodeproj' \
            -scheme 'CardFortress' \
            -destination "platform=iOS Simulator,name=iPhone 15 Pro Max,OS=latest" \
            -derivedDataPath Build/ \
            -enableCodeCoverage YES \
            -allowProvisioningUpdates \
            -verbose \
            build test | xcpretty
          xcrun xccov view --report --json Build/Logs/Test/*.xcresult > coverage.json
          /usr/local/bin/xcc generate coverage.json . cobertura-xml --exclude-packages Tests
      - name: Notify errors on Pull request
        if: ${{ always() }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = 'Some unit tests have failed';
            const comment = context.issue({ body });
            return github.issues.createComment(comment);
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
